Repository Kong/charts, pull requests merged in 2020-02, with the labels that each got.

#35 chore: run tests chart for each branch and PR
  .github/workflows/lint-test.yaml
  .github/workflows/master.yaml
  .github/workflows/non-master.yaml
Labels: please review

#31 [kong] Don't recreate service account
  charts/kong/FAQs.md
  charts/kong/README.md
  charts/kong/templates/migrations-pre-upgrade.yaml
Labels: please review

#12 [kong] Add option to enable HorizontalPodAutoscaler
  charts/kong/README.md
  charts/kong/ci/test1-values.yaml
  charts/kong/templates/hpa.yaml
  charts/kong/values.yaml
Labels: changes requested

#25 [kong] Add warning regarding punctuation in secretVolume names
  charts/kong/values.yaml
Labels: changes requested

#24 kong: Refactor to support mount multiple plugin dir
  charts/kong/templates/_helpers.tpl
  charts/kong/values.yaml
Labels: HOLD/DO NOT MERGE

#34 Helm3 warning
  charts/kong/README.md
Labels: changes requested

#56 feat: add support for priority class
  charts/kong/README.md
  charts/kong/templates/deployment.yaml
  charts/kong/values.yaml
Labels: changes requested
