Repository Kong/charts, pull requests merged in 2020-04, with the labels that each got.

#95 [kong] improve RBAC documentation
  charts/kong/README.md
Labels: changes requested

#110 [kong] correct serviceMonitor.interval docs
  charts/kong/README.md
Labels: pending author response

#115 [kong] remove duplicate `installCRDs` description
  charts/kong/README.md
Labels: please review

#119 [kong] enable kic by default
  charts/kong/templates/_helpers.tpl
Labels: please review

#112 [kong] target proxy with ServiceMonitor selector
  charts/kong/templates/service-kong-proxy.yaml
  charts/kong/templates/servicemonitor.yaml
Labels: please review
