Repository Kong/charts, pull requests merged in 2021-07, with the labels that each got.

#403 [kong] helm chart tests
  .github/workflows/main.yaml
  .github/workflows/non-main.yaml
  charts/kong/templates/tests/test-ingress.yaml
  scripts/test-env.sh
  scripts/test-run.sh
Labels: enhancement

#406 chore: de-duplicate chart test CI runs
  .github/workflows/non-main.yaml
Labels: CI problem

#414 [kong] add toggle for test resources
  charts/kong/templates/tests/test-jobs.yaml
  charts/kong/templates/tests/test-resources.yaml
  charts/kong/values.yaml
  scripts/test-run.sh
  scripts/test-upgrade.sh
Labels: please review

#420 [kong] add watch-namespace automation
  charts/kong/README.md
  charts/kong/templates/_helpers.tpl
  charts/kong/templates/controller-rbac-resources.yaml
  charts/kong/values.yaml
Labels: please review

#426 [kong] fix daemonset values key
  charts/kong/values.yaml
Labels: please review
