Repository Kong/charts, pull requests merged in 2023-11, with the labels that each got.

#931 chore(ingress): bump kong subchart dependency
  charts/ingress/CHANGELOG.md
  charts/ingress/Chart.lock
  charts/ingress/Chart.yaml
Labels: area/release

#947 Split the Deployment without values reorg
  charts/kong/ci/default-values.yaml
  charts/kong/ci/service-account.yaml
  charts/kong/ci/single-image-default-values.yaml
  charts/kong/ci/test1-values.yaml
  charts/kong/ci/test2-values.yaml
  charts/kong/ci/test4-values.yaml
  charts/kong/ci/test5-values.yaml
  charts/kong/templates/_helpers.tpl
  charts/kong/templates/admission-webhook.yaml
  charts/kong/templates/controller-rbac-resources.yaml
  charts/kong/templates/deployment-controller.yaml
  charts/kong/templates/deployment.yaml
  charts/kong/templates/migrations-post-upgrade.yaml
  charts/kong/templates/migrations-pre-upgrade.yaml
  charts/kong/templates/migrations.yaml
  charts/kong/templates/psp.yaml
  charts/kong/templates/secret-sa-token.yaml
  charts/kong/templates/service-account.yaml
  charts/kong/templates/servicemonitor.yaml
  charts/kong/values.yaml
Labels: HOLD/DO NOT MERGE

#955 fix(docs): fix link to controller's CLI reference
  charts/kong/README.md
Labels: documentation
