Repository Kong/charts, pull requests merged in 2023-07, with the labels that each got.

#813 feat(conf): support multiple hosts and tls certificates when kong is…
  charts/kong/CHANGELOG.md
  charts/kong/README.md
  charts/kong/ci/kong-ingress-1-values.yaml
  charts/kong/ci/kong-ingress-2-values.yaml
  charts/kong/ci/kong-ingress-3-values.yaml
  charts/kong/ci/kong-ingress-4-values.yaml
  charts/kong/templates/_helpers.tpl
  charts/kong/templates/ingress-class.yaml
  charts/kong/templates/service-kong-proxy.yaml
  charts/kong/values.yaml
Labels: enhancement

#834 chore: bump postgres to 13.11
  charts/kong/CHANGELOG.md
  charts/kong/Chart.yaml
  charts/kong/values.yaml
Labels: area/maintenance

#835 fix(ingress): make admin api service headless
  charts/ingress/CHANGELOG.md
  charts/ingress/Chart.lock
  charts/ingress/Chart.yaml
  charts/ingress/values.yaml
Labels: area/konnect

#843 fix(ci) update test to agree with new defaults
  scripts/test-run.sh
  scripts/test-upgrade.sh
Labels: area/ci
