Repository Kong/charts, pull requests merged in 2023-05, with the labels that each got.

#793 fix(konnect): do not enable licensing by default
  charts/kong/CHANGELOG.md
  charts/kong/Chart.yaml
  charts/kong/README.md
  charts/kong/templates/_helpers.tpl
  charts/kong/values.yaml
Labels: area/konnect

#796 feat: add RBAC for watching CRDs by controller
  charts/kong/CHANGELOG.md
  charts/kong/Chart.yaml
  charts/kong/templates/_helpers.tpl
Labels: enhancement

#798 chore(rbac): adjust permissions for Endpoints and remove for secrets/status
  charts/kong/CHANGELOG.md
  charts/kong/crds/custom-resource-definitions.yaml
  charts/kong/templates/_helpers.tpl
  charts/kong/templates/controller-rbac-resources.yaml
Labels: area/maintenance

#801 fix(docs): Fix Hybrid mode database value
  charts/kong/README.md
Labels: documentation

#802 chore: CI verisons bump
  .github/workflows/main-pr.yaml
  scripts/test-env.sh
Labels: area/testing, area/ci

#807 fix(ci): migrate from deprecated set-output to using GITHUB_OUTPUT
  .github/workflows/main-pr.yaml
Labels: area/ci

#811 fix(ci): fix ktf install
  scripts/test-env.sh
Labels: area/ci
