Repository Kong/charts, pull requests merged in 2023-08, with the labels that each got.

#849 fix: fix comment in values.yaml
  charts/kong/values.yaml
Labels: area/maintenance

#850 feat: add RBAC rules for KongConsumerGroups
  charts/kong/CHANGELOG.md
  charts/kong/templates/_helpers.tpl
Labels: enhancement

#860 ci: remove k8s 1.19 and 1.20 from tests matrix
  .github/workflows/main-pr.yaml
Labels: area/maintenance, area/ci

#855 chore(ingress): bump chart deps and release 0.5.0
  charts/ingress/CHANGELOG.md
  charts/ingress/Chart.lock
  charts/ingress/Chart.yaml
Labels: area/maintenance, area/release

#861 fix: add CRD KongConsumerGroup and extend status subresource for CRDs
  charts/kong/CHANGELOG.md
  charts/kong/Chart.yaml
  charts/kong/crds/custom-resource-definitions.yaml
Labels: enhancement, area/maintenance, area/release

#865 ci: use ktf for ct related tests
  .github/workflows/main-pr.yaml
  charts/kong/ci/admin-api-service-clusterip-values.yaml
  charts/kong/ci/admin-api-service-clusterip.yaml
  charts/kong/ci/custom-labels-values.yaml
  charts/kong/ci/default-values.yaml
  charts/kong/ci/kong-ingress-1-values.yaml
  charts/kong/ci/kong-ingress-2-values.yaml
  charts/kong/ci/kong-ingress-3-values.yaml
  charts/kong/ci/kong-ingress-4-values.yaml
  charts/kong/ci/single-image-default-values.yaml
  charts/kong/ci/test-enterprise-version-3.4.0.0-values.yaml
  charts/kong/ci/test1-values.yaml
  charts/kong/ci/test2-values.yaml
  charts/kong/ci/test3-values.yaml
  charts/kong/ci/test4-values.yaml
  charts/kong/ci/test5-values.yaml
Labels: area/testing, area/ci

#862 chore(ingress): bump chart deps and release 0.6.0
  charts/ingress/CHANGELOG.md
  charts/ingress/Chart.lock
  charts/ingress/Chart.yaml
Labels: enhancement, area/maintenance, area/release

#876 chore(docs): mention about manual update of kong/ingress deps
  README.md
Labels: documentation, area/maintenance

#878 ingress: add gateway-discovery example and CI values
  .github/workflows/main-pr.yaml
  charts/ingress/ci/gateway-discovery-values.yaml
  charts/ingress/example-values/kic-gateway-discovery.yaml
Labels: documentation, area/ci
