Repository Kong/charts, pull requests merged in 2023-02, with the labels that each got.

#735 fix: make semverCompare handle GKE versions and release 2.16.1
  charts/kong/CHANGELOG.md
  charts/kong/Chart.yaml
  charts/kong/templates/deployment.yaml
  charts/kong/templates/secret-sa-token.yaml
Labels: bug

#749 chore: don't enable clear-stale-pid initContainer when kong isn't deployed
  charts/kong/CHANGELOG.md
  charts/kong/templates/deployment.yaml
Labels: area/maintenance

#752 fix: fix autoscaling version detection
  charts/kong/CHANGELOG.md
  charts/kong/Chart.yaml
  charts/kong/templates/hpa.yaml
Labels: bug

#747 feat: add support for single controller deployments
  charts/kong/CHANGELOG.md
  charts/kong/README.md
  charts/kong/example-values/README.md
  charts/kong/example-values/minimal-kong-sd-controller.yaml
  charts/kong/example-values/minimal-kong-sd-gateway.yaml
  charts/kong/templates/_helpers.tpl
  charts/kong/values.yaml
Labels: enhancement, HOLD/DO NOT MERGE

#746 feat(konnect): allow enabling konnect sync in ingress controller
  charts/kong/CHANGELOG.md
  charts/kong/README.md
  charts/kong/example-values/minimal-kong-controller-konnect.yaml
  charts/kong/templates/_helpers.tpl
  charts/kong/values.yaml
Labels: enhancement, area/konnect

#751 chore(ci): add kube-linter
  .github/workflows/main-pr.yaml
  .kube-linter.yaml
  Makefile
  charts/kong/CHANGELOG.md
  scripts/test-env.sh
  third_party/go.mod
  third_party/go.sum
  third_party/kube-linter.go
Labels: area/maintenance, area/ci

#754 feat(kong): add validation for controller version when using >= 2.9 features
  charts/kong/CHANGELOG.md
  charts/kong/templates/_helpers.tpl
Labels: area/maintenance

#757 feat(kong): do not allow single-pod deployment with gw service discovery
  charts/kong/CHANGELOG.md
  charts/kong/README.md
  charts/kong/example-values/README.md
  charts/kong/templates/_helpers.tpl
Labels: enhancement

#759 feat(konnect): require gw discovery, rename gw discovery and release 2.17.0-rc.1
  charts/kong/CHANGELOG.md
  charts/kong/Chart.yaml
  charts/kong/README.md
  charts/kong/example-values/README.md
  charts/kong/example-values/minimal-kong-controller-konnect.yaml
  charts/kong/example-values/minimal-kong-gd-controller-konnect.yaml
  charts/kong/example-values/minimal-kong-gd-controller.yaml
  charts/kong/example-values/minimal-kong-gd-gateway.yaml
  charts/kong/templates/_helpers.tpl
  charts/kong/values.yaml
Labels: area/maintenance, area/konnect

#761 feat(konnect): allow specifying api hostname in values, release 2.17.0-rc.2
  charts/kong/Chart.yaml
  charts/kong/README.md
  charts/kong/templates/_helpers.tpl
  charts/kong/values.yaml
Labels: area/konnect
