Repository Kong/charts, pull requests merged in 2023-10, with the labels that each got.

#897 fix(ci): report lint problems, auto-update dependencies, etc.
  .github/dependabot.yml
  .github/workflows/lint.yaml
  .github/workflows/main-pr.yaml
  .gitignore
  Makefile
  scripts/test-env.sh
  third_party/go.mod
  third_party/go.sum
Labels: CI problem, area/debt, area/maintenance

#901 chore(tests): bump gateway-api to v0.8.1, move to variable, stop testing with old K8s
  .github/workflows/main-pr.yaml
  charts/kong/templates/tests/test-resources.yaml
  scripts/test-env.sh
Labels: area/testing, area/ci, dependencies

#902 chore: remove redundant $ in docs and `engine` field in Chart.yaml
  charts/ingress/Chart.yaml
  charts/ingress/README.md
  charts/kong/Chart.yaml
  charts/kong/README.md
  charts/kong/UPGRADE.md
Labels: documentation, area/maintenance

#904 chore: fix charts meta and owners
  charts/ingress/Chart.yaml
  charts/kong/OWNERS
Labels: area/maintenance

#905 chore: set team-k8s as maintainers
  charts/ingress/Chart.yaml
  charts/kong/Chart.yaml
Labels: area/maintenance

#907 chore: trigger admission on secrets creation for KIC >= 2.12.1
  charts/kong/CHANGELOG.md
  charts/kong/templates/admission-webhook.yaml
Labels: area/maintenance

#908 chore: use ingressClass field instead of annotation
  charts/ingress/templates/tests/test-resources.yaml
  charts/kong/example-values/doc-examples/quickstart-enterprise-licensed-aio.yaml
  charts/kong/example-values/full-k4k8s-with-kong-enterprise.yaml
  charts/kong/templates/tests/test-resources.yaml
Labels: area/maintenance

#909 feat(sec) add securitycontext restrictions
  charts/kong/README.md
  charts/kong/values.yaml
Labels: HOLD/DO NOT MERGE

#914 feat(kong): allow using templates when specifying `controller.proxy.nameOverride`
  charts/ingress/values.yaml
  charts/kong/CHANGELOG.md
  charts/kong/Chart.yaml
  charts/kong/templates/_helpers.tpl
Labels: enhancement

#915 ingress: allow templating `controller.proxy.nameOverride`
  charts/ingress/CHANGELOG.md
  charts/ingress/Chart.lock
  charts/ingress/Chart.yaml
  charts/ingress/ci/gateway-discovery-values.yaml
  charts/kong/CHANGELOG.md
Labels: area/release

#917 chore(kong): add RBAC for KongUpstreamPolicy
  charts/kong/CHANGELOG.md
  charts/kong/templates/_helpers.tpl
Labels: area/maintenance

#916 docs: add Gateway Discovery DNS strategy docs and example file for ingress chart
  charts/ingress/example-values/kic-gateway-discovery-dns-strategy.yaml
  charts/kong/README.md
Labels: documentation

#918 core(docs): add info about using host network for DaemonSet
  charts/kong/README.md
Labels: documentation

#919 feat: add services to admission webhook config for KIC >= 3.0.0
  .github/workflows/main-pr.yaml
  charts/kong/CHANGELOG.md
  charts/kong/templates/admission-webhook.yaml
Labels: area/maintenance
