Repository Kong/charts, pull requests merged in 2024-01, with the labels that each got.

#978 tests: introduce golden tests in kong chart using chartsnap
  .gitattributes
  .github/workflows/release-pr.yaml
  Makefile
  charts/kong/ci/.chartsnap.yaml
  charts/kong/ci/__snapshots__/admin-api-service-clusterip-values.snap
  charts/kong/ci/__snapshots__/custom-labels-values.snap
  charts/kong/ci/__snapshots__/default-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-1-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-2-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-3-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-4-values.snap
  charts/kong/ci/__snapshots__/service-account.snap
  charts/kong/ci/__snapshots__/single-image-default-values.snap
  charts/kong/ci/__snapshots__/test-enterprise-version-3.4.0.0-values.snap
  charts/kong/ci/__snapshots__/test1-values.snap
  charts/kong/ci/__snapshots__/test2-values.snap
  charts/kong/ci/__snapshots__/test3-values.snap
  charts/kong/ci/__snapshots__/test4-values.snap
  charts/kong/ci/__snapshots__/test5-values.snap
Labels: area/testing, area/ci

#984 ingress: release 0.10.2
  charts/ingress/CHANGELOG.md
  charts/ingress/Chart.lock
  charts/ingress/Chart.yaml
Labels: area/release

#989 fix: explicitly define status port in controller container
  charts/kong/ci/__snapshots__/custom-labels-values.snap
  charts/kong/ci/__snapshots__/default-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-1-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-2-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-3-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-4-values.snap
  charts/kong/ci/__snapshots__/service-account.snap
  charts/kong/ci/__snapshots__/single-image-default-values.snap
  charts/kong/ci/__snapshots__/test1-values.snap
  charts/kong/ci/__snapshots__/test2-values.snap
  charts/kong/ci/__snapshots__/test5-values.snap
  charts/kong/templates/_helpers.tpl
Labels: area/debt

#992 feat: add RBAC rules for KongVault
  charts/kong/CHANGELOG.md
  charts/kong/templates/_helpers.tpl
Labels: area/maintenance
