Repository Kong/charts, pull requests merged in 2024-10, with the labels that each got.

#1141 chore(ci): use 1 namespace for ct install tests
  .github/workflows/release-pr.yaml
Labels: area/testing, area/ci

#1151 feat(kgo): add kubernetes-configuration crds subchart
  charts/gateway-operator/CHANGELOG.md
  charts/gateway-operator/Chart.lock
  charts/gateway-operator/Chart.yaml
  charts/gateway-operator/charts/kubernetes-configuration-crds/Chart.yaml
  charts/gateway-operator/charts/kubernetes-configuration-crds/README.md
  charts/gateway-operator/charts/kubernetes-configuration-crds/crds/kubernetes-configuration-crds.yaml
  charts/gateway-operator/values.yaml
Labels: dependencies, gateway-operator

#1155 chore(kgo): bump kconf-crds dependency
  charts/gateway-operator/Chart.lock
  charts/gateway-operator/Chart.yaml
  charts/gateway-operator/charts/kubernetes-configuration-crds/Chart.yaml
  charts/gateway-operator/charts/kubernetes-configuration-crds/README.md
  charts/gateway-operator/charts/kubernetes-configuration-crds/crds/kubernetes-configuration-crds.yaml
Labels: dependencies
