Repository Kong/charts, pull requests merged in 2024-11, with the labels that each got.

#1161 chore(kgo): bump KGO and kconf
  charts/gateway-operator/CHANGELOG.md
  charts/gateway-operator/Chart.lock
  charts/gateway-operator/Chart.yaml
  charts/gateway-operator/charts/kubernetes-configuration-crds/Chart.yaml
  charts/gateway-operator/charts/kubernetes-configuration-crds/crds/kubernetes-configuration-crds.yaml
  charts/gateway-operator/values.yaml
Labels: area/release

#1165 docs(kgo): use gateway-operator kconf channel
  charts/gateway-operator/UPGRADE.md
  charts/gateway-operator/charts/kubernetes-configuration-crds/README.md
  third_party/go.mod
Labels: area/maintenance

#1169 chore(ci): configure renovate for linters
  .github/workflows/release-pr.yaml
  .tools_versions.yaml
  Makefile
  charts/gateway-operator/scripts/update-rbac-resources.sh
  renovate.json
  scripts/install-chartsnap.sh
  third_party/go.mod
  third_party/go.sum
  third_party/kube-linter.go
Labels: dependencies

#1178 chore(ci): configure renovate for k8s versions
  .github/workflows/release-pr.yaml
  renovate.json
Labels: area/ci

#1179 chore(ci): fix renovate
  .github/workflows/release-pr.yaml
Labels: area/ci

#1180 chore(ci): fix renovate @only-patch
  .github/workflows/release-pr.yaml
  renovate.json
Labels: area/ci

#1182 ci: renovate use kindest/node instead of kubernetes
  .github/workflows/release-pr.yaml
  renovate.json
  scripts/test-env.sh
Labels: area/ci

#1183 ci: fix release-push workflow
  .github/workflows/release-pr.yaml
  .github/workflows/release-push.yaml
Labels: area/ci
