Repository Kong/charts, pull requests merged in 2024-02, with the labels that each got.

#1007 ci: bump helm setup action
  .github/workflows/release-pr.yaml
  .github/workflows/release-push.yaml
Labels: area/maintenance, area/ci

#1011 feat: bump KIC to 3.1, update CRDs and bump Kong to 3.6
  charts/kong/CHANGELOG.md
  charts/kong/Chart.yaml
  charts/kong/ci/__snapshots__/admin-api-service-clusterip-values.snap
  charts/kong/ci/__snapshots__/custom-labels-values.snap
  charts/kong/ci/__snapshots__/default-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-1-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-2-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-3-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-4-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-5-3.1-rbac-values.snap
  charts/kong/ci/__snapshots__/service-account.snap
  charts/kong/ci/__snapshots__/single-image-default-values.snap
  charts/kong/ci/__snapshots__/test-enterprise-version-3.4.0.0-values.snap
  charts/kong/ci/__snapshots__/test1-values.snap
  charts/kong/ci/__snapshots__/test2-values.snap
  charts/kong/ci/__snapshots__/test3-values.snap
  charts/kong/ci/__snapshots__/test4-values.snap
  charts/kong/ci/__snapshots__/test5-values.snap
  charts/kong/crds/custom-resource-definitions.yaml
  charts/kong/values.yaml
Labels: area/release

#1013 ingress: bump kong/kong dependency, release 0.11.1
  charts/ingress/CHANGELOG.md
  charts/ingress/Chart.lock
  charts/ingress/Chart.yaml
Labels: area/maintenance, area/release
