Repository Kong/charts, pull requests merged in 2025-03, with the labels that each got.

#1263 feat: add `ValidatingAdmissionPolicy` validating `DataPlane` ports
  charts/gateway-operator/CHANGELOG.md
  charts/gateway-operator/Chart.yaml
  charts/gateway-operator/ci/__snapshots__/affinity-values.snap
  charts/gateway-operator/ci/__snapshots__/disable-gateway-controller-values.snap
  charts/gateway-operator/ci/__snapshots__/env-and-args-values.snap
  charts/gateway-operator/ci/__snapshots__/env-and-customenv-values.snap
  charts/gateway-operator/ci/__snapshots__/extra-labels-values.snap
  charts/gateway-operator/ci/__snapshots__/kube-rbac-proxy-removed-in-1-5-values.snap
  charts/gateway-operator/ci/__snapshots__/nightly-can-be-used-values.snap
  charts/gateway-operator/ci/__snapshots__/probes-and-args-values.snap
  charts/gateway-operator/ci/__snapshots__/tolerations-values.snap
  charts/gateway-operator/templates/validation-policy-dataplane.yaml
  charts/ingress/ci/__snapshots__/gateway-discovery-values.snap
Labels: enhancement

#1272 ci: remove old version integration tests
  .github/workflows/release-pr.yaml
Labels: area/ci

#1280 chore: document how to disable webhook in kube-system ns
  charts/kong/FAQs.md
Labels: documentation

#1279 docs(kgo): add 0.5.0 update instructions
  charts/gateway-operator/UPGRADE.md
Labels: documentation
