Repository Kong/charts, pull requests merged in 2025-01, with the labels that each got.

#1211 chore: change pattern of autogenerated `ValidatingWebhookConfiguration` name
  charts/kong/CHANGELOG.md
  charts/kong/ci/.chartsnap.yaml
  charts/kong/ci/__snapshots__/admission-webhook-configuration.snap
  charts/kong/ci/__snapshots__/custom-entities-rbac-3.2-values.snap
  charts/kong/ci/__snapshots__/custom-labels-values.snap
  charts/kong/ci/__snapshots__/default-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-1-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-2-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-3-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-4-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-5-3.1-rbac-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-5-3.4-rbac-values.snap
  charts/kong/ci/__snapshots__/proxy-appprotocol-values.snap
  charts/kong/ci/__snapshots__/service-account.snap
  charts/kong/ci/__snapshots__/single-image-default-values.snap
  charts/kong/ci/__snapshots__/test1-values.snap
  charts/kong/ci/__snapshots__/test2-values.snap
  charts/kong/ci/__snapshots__/test5-values.snap
  charts/kong/templates/admission-webhook.yaml
Labels: enhancement

#1212 Chore(ci): pin 3rd party actions by hashes
  .github/workflows/release-pr.yaml
  .github/workflows/release-push.yaml
Labels: area/ci

#1221 chore: ensure action versions are pinned
  .github/workflows/master-mirrors-main.yaml
  .github/workflows/release-pr.yaml
  .github/workflows/release-push.yaml
Labels: area/ci

#1220 tests: add Gateway API capability to chartsnap invocation
  Makefile
  charts/ingress/ci/__snapshots__/gateway-discovery-values.snap
  charts/ingress/ci/__snapshots__/kic-3.4-values.snap
  charts/kong/ci/__snapshots__/admission-webhook-configuration.snap
  charts/kong/ci/__snapshots__/custom-entities-rbac-3.2-values.snap
  charts/kong/ci/__snapshots__/custom-labels-values.snap
  charts/kong/ci/__snapshots__/default-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-1-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-2-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-3-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-4-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-5-3.1-rbac-values.snap
  charts/kong/ci/__snapshots__/kong-ingress-5-3.4-rbac-values.snap
  charts/kong/ci/__snapshots__/proxy-appprotocol-values.snap
  charts/kong/ci/__snapshots__/service-account.snap
  charts/kong/ci/__snapshots__/single-image-default-values.snap
  charts/kong/ci/__snapshots__/test1-values.snap
  charts/kong/ci/__snapshots__/test2-values.snap
  charts/kong/ci/__snapshots__/test5-values.snap
Labels: area/testing, area/ci

#1222 chore: remove master-main sync workflow
  .github/workflows/master-mirrors-main.yaml
  .github/workflows/release-pr.yaml
  charts/kong/example-values/minimal-kong-enterprise-dbless.yaml
  charts/kong/example-values/minimal-kong-enterprise-hybrid-control.yaml
  charts/kong/example-values/minimal-kong-enterprise-hybrid-data.yaml
Labels: area/ci

#1227 ci: limit permissions of GITHUB_TOKEN and add actionlint
  .github/workflows/release-pr.yaml
  .github/workflows/release-push.yaml
  .tools_versions.yaml
  Makefile
Labels: area/ci

#1231 chore(deps): bump kong/kubernetes-configuration to v1.0.7
  charts/gateway-operator/CHANGELOG.md
  charts/gateway-operator/Chart.lock
  charts/gateway-operator/Chart.yaml
  charts/gateway-operator/charts/kubernetes-configuration-crds/Chart.yaml
  charts/gateway-operator/charts/kubernetes-configuration-crds/crds/kubernetes-configuration-crds.yaml
  charts/gateway-operator/ci/__snapshots__/affinity-values.snap
  charts/gateway-operator/ci/__snapshots__/disable-gateway-controller-values.snap
  charts/gateway-operator/ci/__snapshots__/env-and-args-values.snap
  charts/gateway-operator/ci/__snapshots__/env-and-customenv-values.snap
  charts/gateway-operator/ci/__snapshots__/extra-labels-values.snap
  charts/gateway-operator/ci/__snapshots__/probes-and-args-values.snap
  charts/gateway-operator/ci/__snapshots__/tolerations-values.snap
Labels: area/maintenance, area/release

#1232 chore(ci): don't run lint-test before release in release workflow
  .github/workflows/release-push.yaml
Labels: area/ci

#1233 ci: configure renovate for KIND_VERSION
  .github/workflows/release-pr.yaml
  renovate.json
Labels: area/ci

#1238 chore(kgo): bump kong/kubernetes-configuration to v1.0.8
  charts/gateway-operator/CHANGELOG.md
  charts/gateway-operator/Chart.lock
  charts/gateway-operator/Chart.yaml
  charts/gateway-operator/charts/kubernetes-configuration-crds/Chart.yaml
  charts/gateway-operator/charts/kubernetes-configuration-crds/crds/kubernetes-configuration-crds.yaml
  charts/gateway-operator/ci/__snapshots__/affinity-values.snap
  charts/gateway-operator/ci/__snapshots__/disable-gateway-controller-values.snap
  charts/gateway-operator/ci/__snapshots__/env-and-args-values.snap
  charts/gateway-operator/ci/__snapshots__/env-and-customenv-values.snap
  charts/gateway-operator/ci/__snapshots__/extra-labels-values.snap
  charts/gateway-operator/ci/__snapshots__/probes-and-args-values.snap
  charts/gateway-operator/ci/__snapshots__/tolerations-values.snap
Labels: area/maintenance
